### ISSUE TITLE
Plan to Publish?  Taking PR's?

### ISSUE THREAD

**Issue by bbrandt** [lucasvieirasilva/nx-plugins#1]
Hello @lucasvieirasilva,

I have been looking for a Nx Plugin for Python development, but most plugins seems to no longer be supported.  What's your outlook on this repository?  I like your approach of using Poetry for dependency management.  Are you accepting pull requests if I work up the courage to be able to contribute anything?

Thanks!

**Comment by lucasvieirasilva** [comment]
Hi @bbrandt, I appreciate your interest in my Nx plugin, I'm happy to receive pull requests, thanks

**Comment by niall-mediasuite** [comment]
Just to further this conversation. What's the goal for this plugin? Do you want it to become the community plugin for nx and Python or is this just to support your requirements.

In playing around with the plugin I have noticed there is a bunch of assumptions around the functionality desired. In particular with the build step and pulling in local dependencies. To use it we would need to make some modifications to simplify the behaviour and make it more generic. However I'm not sure if that's the direction you want to take this project. We are happy to fork and maintain our own version if that's what you would prefer.

**Comment by lucasvieirasilva** [comment]
@niall-mediasuite At first, I created this project to use in my projects, however, I’d love to see this project becoming a community plugin.
Let's discuss what modifications we need to do to make this project more generic, I'm happy to do those modifications or review PRs if you want to contribute as well.

**Comment by niall-mediasuite** [comment]
Ok, thanks for the clarification. I'll open another feature request which is specific to the issue I'm currently facing.
