### ISSUE TITLE
Chained library dependencies break `pip download`

### ISSUE THREAD

**Issue by scottanderson42** [lucasvieirasilva/nx-plugins#101]
### Current Behavior

AWS SAM's build command downloads everything in the `requirements.txt` to a temporary directory, then runs its build over that directory when it creates the deployment package.

The current setup for the `pyproject.toml` files use `../some-lib` as the dependency path between local libraries, which can't be resolved by pip when it's doing a download when there is more than one level of local library dependencies. If I change these references to the wheel files (eg. `../../libs/test_two/dist/test_two-1.0.0-py3-none-any.whl`) then the pip error goes away, but changes to the local libraries are not reflected after builds because pip thinks that the wheels haven't changed based on the version number of the wheel.

If the application references a local library that does not have any upstream local libraries, `pip download` does not fail.

### Expected Behavior

Chained local library dependencies should work for `pip download` and other pip commands that use `pyproject.toml` to resolve dependencies.

### Steps to Reproduce

```
$ npx nx generate @nxlv/python:project test-one --type library --packageName=test-one --moduleName=test_one
$ npx nx generate @nxlv/python:project test-two --type library --packageName=test-two --moduleName=test_two
$ npx nx run test-two:add --name test-one --local
$ npx nx generate @nxlv/python:project test-app --type application --packageName=test-app --moduleName=test_app
$ npx nx run test-app:add --name test-two --local
$ cd apps/test-app
$ poetry export -f requirements.txt --without-hashes --output requirements.txt
$ cat requirements.txt
test-one @ file:///Users/me/src/test-python/libs/test-one ; python_version >= "3.8" and python_version < "3.11"
test-two @ file:///Users/me/src/test-python/libs/test-two ; python_version >= "3.8" and python_version < "3.11"

$ pip download -r requirements.txt --dest tmp
Processing /Users/me/src/test-python/libs/test-one (from -r requirements.txt (line 1))
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Processing /Users/me/src/test-python/libs/test-two (from -r requirements.txt (line 2))
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
ERROR: Exception:
Traceback (most recent call last):
  File "/Users/me/.pyenv/versions/3.8.11/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3108, in _dep_map
    return self.__dep_map
  File "/Users/me/.pyenv/versions/3.8.11/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2901, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/me/.pyenv/versions/3.8.11/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 169, in exc_logging_wrapper
    status = run_func(*args)
  File "/Users/me/.pyenv/versions/3.8.11/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 248, in wrapper
    return func(self, options, args)
  File "/Users/me/.pyenv/versions/3.8.11/lib/python3.8/site-packages/pip/_internal/commands/download.py", line 132, in run
    requirement_set = resolver.resolve(reqs, check_supported_wheels=True)
  File "/Users/me/.pyenv/versions/3.8.11/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "/Users/me/.pyenv/versions/3.8.11/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/Users/me/.pyenv/versions/3.8.11/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 427, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "/Users/me/.pyenv/versions/3.8.11/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 239, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
  File "/Users/me/.pyenv/versions/3.8.11/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 229, in _get_updated_criteria
    for requirement in self._p.get_dependencies(candidate=candidate):
  File "/Users/me/.pyenv/versions/3.8.11/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/provider.py", line 244, in get_dependencies
    return [r for r in candidate.iter_dependencies(with_requires) if r is not None]
  File "/Users/me/.pyenv/versions/3.8.11/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/provider.py", line 244, in <listcomp>
    return [r for r in candidate.iter_dependencies(with_requires) if r is not None]
  File "/Users/me/.pyenv/versions/3.8.11/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 241, in iter_dependencies
    requires = self.dist.iter_dependencies() if with_requires else ()
  File "/Users/me/.pyenv/versions/3.8.11/lib/python3.8/site-packages/pip/_internal/metadata/pkg_resources.py", line 216, in iter_dependencies
    return self._dist.requires(extras)
  File "/Users/me/.pyenv/versions/3.8.11/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2821, in requires
    dm = self._dep_map
  File "/Users/me/.pyenv/versions/3.8.11/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3110, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/Users/me/.pyenv/versions/3.8.11/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3121, in _compute_dependencies
    reqs.extend(parse_requirements(req))
  File "/Users/me/.pyenv/versions/3.8.11/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3174, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/Users/me/.pyenv/versions/3.8.11/lib/python3.8/site-packages/pip/_vendor/packaging/requirements.py", line 118, in __init__
    raise InvalidRequirement(f"Invalid URL: {req.url}")
pip._vendor.packaging.requirements.InvalidRequirement: Invalid URL: ../test-one
```

### Nx Report

```shell
Node : 16.14.2
   OS   : darwin arm64
   npm  : 8.5.0

   nx : 15.6.2
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.6.2
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.6.2
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : Not Found
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.6.3
   @nrwl/js : 15.9.2
   @nrwl/linter : Not Found
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.9.2
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.6.2
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.9.2
   @nrwl/web : 15.6.2
   @nrwl/webpack : 15.9.2
   @nrwl/workspace : 15.6.2
   @nrwl/vite : Not Found
   typescript : 5.0.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
   	 @nxlv/python: 15.7.0
```

### Additional Information

As a workaround, `pip download` works if I remove the lines referencing the local library wheels from the exported `requirements.txt`. 

EDIT: I thought was working but it turns out it isn't. I don't have a workaround at this point.

**Comment by lucasvieirasilva** [comment]
Hey @scottanderson42, thanks for sharing this issue.

If you use poetry commands it is not going to have the wrappers to resolve local dependencies that this plugin has, to do what you described, you should try.

1. Run `npx nx build test-app`

This command is going to resolve all the local dependencies and create a `.whl` file.

2. Run `find ./dist -name '*.whl' | head -n 1 > requirements.txt` to reference the whl file in the requirements.txt

By doing that SAM is going to use the whl file to install all the dependencies, including all the local ones.

you can also create an nx target for doing that.

edit your `apps/test-app/project.json` to add the following target:

```json
{
  "name": "test-app",
  ...
  "targets": {
    "sam-package": {
      "executor": "nx:run-commands",
      "options": {
        "commands": [
          "rm -f requirements.txt",
          "find ./dist -name '*.whl' | head -n 1 > requirements.txt"
        ],
        "parallel": false,
        "cwd": "apps/test-app"
      },
      "dependsOn": [
        {
          "target": "build",
          "projects": "self"
        }
      ]
    },
    ...
  }
}

```

And run the following command: `npx nx sam-package test-app`

can you try and let me know if that work for you?

Thanks

**Comment by scottanderson42** [comment]
That doesn't have the pip error, thanks. However, proceeding further in my testing, if I change something in the code for `test-two` and re-run `npx nx sam-package test-app`, the wheel does not get rebuilt as I would expect (and need). It still contains the previous code from the `test-two` library.

**Comment by lucasvieirasilva** [comment]
Hey @scottanderson42, I think I made a mistake, in the `project.json` that I provided you, the `dependsOn` property should have the `^build` instead of the object

The way I provided it to you means the Nx is gonna build the dependent projects, but you need the actual project to be built, which should provide the wheel file if all the changes, including the local dependency projects.

Could you try in this way pls? 

```json
{
  "name": "test-app",
  ...
  "targets": {
    "sam-package": {
      "executor": "nx:run-commands",
      "options": {
        "commands": [
          "rm -f requirements.txt",
          "find ./dist -name '*.whl' | head -n 1 > requirements.txt"
        ],
        "parallel": false,
        "cwd": "apps/test-app"
      },
      "dependsOn": ["^build"]
    },
    ...
  }
}

```

**Comment by lucasvieirasilva** [comment]
Hey @scottanderson42, you're welcome, right, tomorrow morning I'm going to reproduce this issue locally, it should work with this fix.

I'll let you know!

**Comment by lucasvieirasilva** [comment]
Hey @scottanderson42, I was right in the first `project.json` that I provided to you, in the `dependsOn.projects` property it is specified the `self` value and that is exactly what makes Nx rebuild the project.

What I explained yesterday about only building the dependencies projects is only true if you use `dependsOn.projects` property with the value `dependencies`.

```json
{
  "name": "test-app",
  ...
  "targets": {
    "sam-package": {
      "executor": "nx:run-commands",
      ...
      "dependsOn": [
        {
          "target": "build",
          "projects": "self"
        }
      ]
    },
    ...
  }
}
```

When you installed the `@nxlv/python` plugin, have you changed the `nx.json` to add the `plugins` property?

```json
{
  "extends": "nx/presets/npm.json",
  "$schema": "./node_modules/nx/schemas/nx-schema.json",
  "plugins": ["@nxlv/python"],
  ...
}
```

If not, this step is required to make Nx consider the `@nxlv/python` logic to resolve the dependency tree.

Could you check and let me know?

**Comment by scottanderson42** [comment]
Yes, the plugin is installed:

```
  "plugins": [
    "@nrwl/js",
    "@nxlv/python"
  ],
```
I started a brand-new nx workspace (in 16.2.2, but we're running 15.6.2). I created the test projects as above and then:

1. I added and ran the `sam-package` target, which created the wheel file and `requirements.txt` with the proper code.
2. I changed `packages/test-two/test_two/index.py`.
3. I ran `sam-package` and it properly created the wheel file with the changed code.

Next I did the same, but with nx 15.6.2:
1. I added the `sam-package` target and ran it successfully.
2. I changed the `index.py` in `test-two` as before and re-ran `sam-package`, this worked properly and used the changed code.
3. I did the same for `test-one`, and it also worked.

So far so good. Now here's the weird part: 
- I copied my original repository into a new directory and verified that it did not rebuild the wheel file after a change was made to `test-two`.
-  I started whittling down this new installation, and after a few hours of painstakingly running compares, paring away files, and so on, I discovered that it was the presence of another app besides `test-app`, and all that other app needs to have is an empty `pyproject.toml` and a `project.json` that consists of only `{}`.
- I added a blank app named `rhubarb` to the working bare nx 15 workspace and added the blank `pyproject.toml` and minimal `project.json`. Then I removed the cache and ran `nx reset`, made a change, ran `sam-package` to fill the cache, verified the wheel was rebuilt properly, I made another change to `test-two`, ran `sam-package`, and it would not rebuild the wheel.

Comparing the `node_modules/.cache/nx/nxdeps.json` between the working and non-working setups:

Good:
```
  "dependencies": {
    "test-app": [
      {
        "source": "test-app",
        "target": "test-two",
        "type": "implicit"
      }
    ],
    "test-one": [],
    "test-two": [
      {
        "source": "test-two",
        "target": "test-one",
        "type": "implicit"
      }
    ],
```

Bad:
```
  "dependencies": {
    "test-app": [],
    "test-one": [],
    "test-two": [],
    "rhubarb": [],
```

If you are going to test this yourself, remember to clear the `.cache` directory and run `nx reset` between adding or removing the extra empty app so it can rebuild the cache incorrectly/correctly.

Here's the `nx.json` I'm using, which just has the `cacheableOperations` and `workspaceLayout` changed:
```
{
  "tasksRunnerOptions": {
    "default": {
      "runner": "nx/tasks-runners/default",
      "options": {
        "cacheableOperations": ["build", "test", "lint"]
      }
    }
  },
  "workspaceLayout": {
    "appsDir": "apps",
    "libsDir": "libs"
  },
  "plugins": [
    "@nxlv/python"
  ]
}
```

**Comment by scottanderson42** [comment]
I didn't, but that's because it's an existing Python app in our repository that uses a different build because it needs Docker. I just started using @nxlv/python because I was looking for a more standardized way of building Python without Docker.

**Comment by lucasvieirasilva** [comment]
got it, looks like I assume if the project has a `pyproject.toml` it needs to have the poetry structure, I'm fixing this assumption

**Comment by scottanderson42** [comment]
Here's the full one in case it helps; it doesn't seem to matter what's in the `pyproject.toml` so long as it isn't `@nxlv/python`'s.

```
[tool.poetry]
name = "rhubarb"
version = "0.1.0"
description = ""

[tool.poetry.dependencies]
python = "^3.8"
torch = "1.12.1"
torchvision = "^0.12.0"
aws-lambda-powertools = "^1.26.0"
awslambdaric = "^2.0.4"
Pillow = "^9.1.1"
tqdm = "^4.64.0"
ftfy = "^6.1.1"
regex = "^2022.6.2"
ortools = "9.3.10497"
tokenizers = "0.10.2"
cachetools = "^5.2.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
moto = "^3.1.13"
PyYAML = "^6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = "-p no:warnings"
```

**Comment by lucasvieirasilva** [comment]
Yeah, it helps, many thanks for sharing this

**Comment by lucasvieirasilva** [comment]
@scottanderson42 when I use the `pyproject.toml` that you provided, the `nxdeps.json` is generated with the correct values:

```json
"test-app": [
      {
        "source": "test-app",
        "target": "test-two",
        "type": "implicit"
      }
    ],
    "test-one": [],
    "test-two": [
      {
        "source": "test-two",
        "target": "test-one",
        "type": "implicit"
      }
    ],
    "rhubard": []
```

Only when I leave the `pyproject.toml` empty I can reproduce the issue.

I'm using Nx 15 here.

**Comment by scottanderson42** [comment]
Make sure you clear the cache and reset nx after you add the additional app:

`rm -rf node_modules/.cache/nx ; npx nx reset`

If you don't do that then it will hang on to the working `nxdeps.json`.

**Comment by lucasvieirasilva** [comment]
Yep, I did that

**Comment by lucasvieirasilva** [comment]
![May-29-2023 16-37-16](https://github.com/lucasvieirasilva/nx-plugins/assets/12723594/abd99f45-4dd9-40b6-a966-d55eab0cc2dd)

**Comment by scottanderson42** [comment]
It turns out there are two ways it fails:
1. with an empty `pyproject.toml`
2. with a `pyproject.toml` that contains a relative path (note the line for `blip`):

```
[tool.poetry]
name = "rhubarb"
version = "0.1.0"
description = ""
license = "Proprietary"

[tool.poetry.dependencies]
python = "^3.8"
torch = "1.12.1"
torchvision = "^0.12.0"
aws-lambda-powertools = "^1.26.0"
awslambdaric = "^2.0.4"
Pillow = "^9.1.1"
tqdm = "^4.64.0"
ftfy = "^6.1.1"
regex = "^2022.6.2"
ortools = "9.3.10497"
blip = {path = "../../libs/blip"}
tokenizers = "0.10.2"
cachetools = "^5.2.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
moto = "^3.1.13"
PyYAML = "^6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = "-p no:warnings"
```

I had a few copies of this lying around as I was testing things and managed to give you the one that works. 🙃

It doesn't seem to matter if that `blip` path is missing, present but empty, or present with an `__init__.py` in it.

**Comment by lucasvieirasilva** [comment]
hmm, now makes more sense, I'll let you know as soon as possible.

**Comment by lucasvieirasilva** [comment]
Hey @scottanderson42 I've published a beta version with the fix:

https://www.npmjs.com/package/@nxlv/python/v/15.9.1-beta.1

Could you check if that solves your issue?

Thanks

**Comment by scottanderson42** [comment]
@lucasvieirasilva Yes, that works in my test projects! Getting it into the original repo will take a bit more work but I'll let you know.

**Comment by lucasvieirasilva** [comment]
@scottanderson42 nice, I'm working on the unit tests in the meantime.

**Comment by scottanderson42** [comment]
Looks good so far! \o/ Thanks so much for your help.

**Comment by lucasvieirasilva** [comment]
You're welcome, I'm gonna merge the PR and release the version
