### ISSUE TITLE
Allow overriding or customizing the template files

### ISSUE THREAD

**Issue by scottanderson42** [lucasvieirasilva/nx-plugins#111]
- [x ] I'd be willing to implement this feature

## Description

Allowing the generator files to be modified automatically to include or omit features.

## Motivation

There are any number of customizations we'd like to make to the project generators, such as creating a SAM `template.yaml`, adding specific sections or configuration to `pyproject.toml`, adding or modifying tasks in `project.json`, and so on. We could create our own generator that calls the `@nxlv` generator, but that seems wasteful and somewhat difficult if all we need to do is, for example, change the pytest configuration.

## Suggested Implementation

Passing in a simple `--template-files-dir` that overrides the location of the template files. Or somewhat more complicated, only overrides the files that are present in the additional directory. This would introduce a minimal maintenance burden.

## Alternate Implementations

There may be `nx` conventions for generators of which I am unaware, but some other approaches are:
- Add a `features` parameter to the generators that is used to toggle the presence of sections of the files or modify behavior, similar to `addDevDependencies` but generalized. Additional features would require code additions though.
- Ensure that each of the functions used to perform actions in the current generator are exported and composable by another generator. An example would be the project configuration object, which is both created and directly used in the project generator function. An exported function that returns a default configuration suitable for modification would be useful to call from another generator.

**Comment by lucasvieirasilva** [comment]
Hey @scottanderson42, I agree, currently, the project generator is not customizable enough, let me research a little bit, look at how Nx does for their own generators, and discuss with you more about it.

I agree that could be not productive if you write your generator trying to remove or modify the current generator, another suggestion might be a light version of the project generator that only generates a minimal number of files, in this way, it is easy to extend the `@nxlv` generator to your uses cases without any workaround to change what the base generator created.

Sounds good?

**Comment by scottanderson42** [comment]
Sounds good to me!

**Comment by lucasvieirasilva** [comment]
Hey @scottanderson42 sorry for the delay, I finally had the time to raise the PR that implements a new project generator, more flexible, I also used your suggestion to have the `--templateDir` CLI option to point for a custom template directory.

PR: https://github.com/lucasvieirasilva/nx-plugins/pull/123

It also fixes #117 because I'm not installing the `tomli` anymore.
