### ISSUE TITLE
Migrating nrwl to nx

### ISSUE THREAD

**Issue by maxime4000** [lucasvieirasilva/nx-plugins#121]
- [ ] I'd be willing to implement this feature

## Description
So I'm using @nxlv/python. Just want to know if you were considering to update your nx packages

https://blog.nrwl.io/nx-16-is-here-69584ec87053

## Motivation
```
 >  NX   Cannot find module '@nrwl/devkit'

   Require stack:
   - /project/node_modules/@nxlv/python/src/graph/dependency-graph.js
   - /project/node_modules/@nxlv/python/src/index.js
   - /project/node_modules/nx/src/utils/nx-plugin.js
 ```

**Comment by lucasvieirasilva** [comment]
Hey @maxime4000, sure, I'm working on this issue #111, your request is gonna be the next one.
