### ISSUE TITLE
Cannot set python version to 3.11 with shared-env

### ISSUE THREAD

**Issue by kennysliding** [lucasvieirasilva/nx-plugins#168]
### Current Behavior

I am trying to use python 3.11 with shared-env, I have updated the pyproject and .python-version to use `~=3.11.5` but whenever I run `nx generate @nxlv/python:migrate-to-shared-venv`, it will change the version in `pyproject.toml` into `  python = ">=3.9,<3.11"` and .python-version to `3.9.5` and failed the command since I don't have 3.9.5 installed locally

### Expected Behavior

To use 3.11.5 when running `nx generate @nxlv/python:migrate-to-shared-venv`

### Steps to Reproduce

None

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.16.0
   OS     : darwin-arm64
   npm    : 9.5.1
   
   nx (global)  : 16.7.4
   nx           : 16.7.3
   @nx/devkit   : 16.7.4
   @nrwl/tao    : 16.7.3
   ---------------------------------------
   Community plugins:
   @nxlv/python : 16.1.2
   ---------------------------------------
   The following packages should match the installed version of nx
     - @nx/devkit@16.7.4
     - @nrwl/devkit@16.7.4
   
   To fix this, run `nx migrate nx@16.7.4`
```

**Comment by lucasvieirasilva** [comment]
Hi @kennysliding thanks for opening this issue.

There are 2 ways you can generate projects with different Python versions.

1. Providing `--pyenvPythonVersion` and `--pyprojectPythonDependency` CLI commands in the `npx nx g @nxlv/python:poetry-project` command.

Example:

```shell
npx nx g @nxlv/python:poetry-project myapp --pyenvPythonVersion "3.11.5"  --pyprojectPythonDependency ">=3.9,<3.12"
```

**NOTE**: The same properties are available in the Nx VSCode extension.

![image](https://github.com/lucasvieirasilva/nx-plugins/assets/12723594/1f13ab22-d436-4136-a654-3264797e7512)

2. Modifying the `nx.json` and changing the default values, so, when you run `npx nx g @nxlv/python:poetry-project myapp` the default values are going to be yours.

`nx.json`

```json
{
  ...
  "generators": {
    "@nxlv/python:poetry-project": {
      "pyenvPythonVersion": "3.11.5",
      "pyprojectPythonDependency": ">=3.9,<3.12"
    }
  }
  ...
}
```

Reference: https://nx.dev/reference/nx-json#generators

The same with the `migrate-to-shared-venv`, you can provide `--pyenvPythonVersion` and `--pyprojectPythonDependency` CLI options or use the `nx.json` default values:

`nx.json`

```json
{
  ...
  "generators": {
    "@nxlv/python:migrate-to-shared-venv": {
      "pyenvPythonVersion": "3.11.5",
      "pyprojectPythonDependency": ">=3.9,<3.12"
    }
  }
  ...
}
```

Please let me know if that solves the issue.

Thanks!

**Comment by kennysliding** [comment]
Thanks so much for the explanation, this has been a great help! @lucasvieirasilva

I have solved my issue by running 

`nx generate @nxlv/python:migrate-to-shared-venv --pyenvPythonVersion "3.11.5"  --pyprojectPythonDependency "~=3.11.5"`

since I would like be to stricter on the version

Thanks so much for your help!

**Comment by johnnymo87** [comment]
I partially setup an Nx workspace for python, but then hit some snags related to pushing the python version to `~=3.11.5`. This discussion helped me, but I had to make one more change. In addition to modifying the `nx.json`, I had to modify a line in my`pyproject.toml` in the project root to read as follows:
```
  [tool.poetry.dependencies]
  python = "~=3.11.5"
```

**Comment by mklueh** [comment]
Same here:

> nx generate @nxlv/python:migrate-to-shared-venv

Overwrites the pyproject.toml settings to

```
  [tool.poetry.dependencies]
  python = ">=3.9,<3.11"
```

and then fails with

```

 NX  Generating @nxlv/python:migrate-to-shared-venv

UPDATE pyproject.toml
  Updating myproject poetry.lock...
Resolving dependencies... (1.2s)

  poetry.lock updated.

  Updating root poetry.lock...

Current Python version (3.11.9) is not allowed by the project (>=3.9,<3.11).
Please change python executable via the "env use" command.

 NX   poetry install command failed with exit code 1

Pass --verbose to see the stacktrace.

```
