### ISSUE TITLE
Support for ruff

### ISSUE THREAD

**Issue by AbdealiLoKo** [lucasvieirasilva/nx-plugins#170]
- [ ] I'd be willing to implement this feature

## Description
I see flake8 is supported - would be good to have ruff support as well

## Motivation
ruff is becoming popular and much faster than flake8 :)

## Suggested Implementation
Im not too good with nx plugins ... but I think a new "executor" which handles ruff ?

## Alternate Implementations
use the ol' `run-command` in nx would be an alternative that works

**Comment by lucasvieirasilva** [comment]
Hey @AbdealiLoKo, sorry about the delay, I've been pretty busy with other stuff lately, but I'm gonna spend some time next week on the 2 issues you opened (the other one is #171).

Thanks!

**Comment by AbdealiLoKo** [comment]
Sure ! Thanks :)

Happy to discuss my project setup and test / help as much as possible

**Comment by lucasvieirasilva** [comment]
@AbdealiLoKo sorry for the delay again, I've been extremely busy lately, and I just added the ruff support, I see you have another issue open, I'm gonna try my best to look at it next week.
