### ISSUE TITLE
docs(nx-python): how to contribute

### ISSUE THREAD

**Issue by busla** [lucasvieirasilva/nx-plugins#178]
### Documentation issue

I am trying to setup `nx-python` locally in dev mode (`npm/yarn link`) but am running into issues. I think it would be beneficial for the project to add a _How to contribute_ chapter in the docs.

**Comment by lucasvieirasilva** [comment]
Hey, sorry for the delay, I've been very busy lately, yes, I agree 100% with you, I'm going to raise a PR for that.
