### ISSUE TITLE
Shared virtual environment cannot install

### ISSUE THREAD

**Issue by kylebjordahl** [lucasvieirasilva/nx-plugins#187]
### Current Behavior

When installing the root directory to provide the shared virtual environment, poetry complains because I don't have an actuall root module to install (the root directory doesn't have any actual code)

> The Nx workspace is named `ohm` in my failure logs

I believe the missing piece would be to add `--no-root` as a flag to the install for the shared virtual environment. Perhaps this can be an optional config somehow

### Expected Behavior

Install of virtual environment should work without error.

### Steps to Reproduce

Set up a shared virtual environment without any `[tool.poetry.packages]` entry in the root `pyproject.toml`

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 16.20.2
   OS     : linux-arm64
   npm    : 8.19.4
   
   nx                 : 16.7.4
   @nx/js             : 16.7.4
   @nx/jest           : 16.7.4
   @nx/linter         : 16.7.4
   @nx/workspace      : 16.7.4
   @nx/cypress        : 16.7.4
   @nx/devkit         : 16.7.4
   @nx/eslint-plugin  : 16.7.4
   @nx/plugin         : 16.7.4
   @nx/react          : 16.7.4
   @nx/storybook      : 16.7.4
   @nrwl/tao          : 16.7.4
   @nx/web            : 16.7.4
   @nx/webpack        : 16.7.4
   nx-cloud           : 16.3.0
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @nxlv/python : 16.1.2
   nx-stylelint : 15.0.0
   ---------------------------------------
   Local workspace plugins:
         @ohm/nx-helpers
```

### Failure Logs

```shell
UPDATE pyproject.toml
  Updating root poetry.lock...
Resolving dependencies... (5.1s)

Writing lock file
Running command: poetry install 

Installing dependencies from lock file

No dependencies to install or update

Installing the current project: ohm (1.0.0)
The current project could not be installed: No file/folder found for package ohm
If you do not want to install the current project use --no-root

  poetry.lock updated.
```

**Comment by kylebjordahl** [comment]
BTW I am able to generate successfully if I modify the `poetry-project/generator:updateRootPoetryLock` locally and add the `--no-root` flag to the `install` command

**Comment by lucasvieirasilva** [comment]
Hey @kylebjordahl sorry for the delay, I've been pretty busy lately, so, I tried to reproduce it locally using the Nx version you provided in the logs and it's working fine.

I'm using poetry version `1.5.1`, which Poetry version are you using?

![image](https://github.com/lucasvieirasilva/nx-plugins/assets/12723594/df4d0a14-5d1d-4c28-b24a-97b579de60bc)

**Comment by kylebjordahl** [comment]
Hi @lucasvieirasilva, sorry for the huge delay, days after I opened this issue we my daughter was born and I have had zero time to follow up. 

Just today I discovered that there is a [poetry setting](https://python-poetry.org/docs/pyproject/#package-mode) which can solve this, so this issue can be safely closed.

**Comment by lucasvieirasilva** [comment]
Hey @kylebjordahl no problems, this is much more important than this issue, congrats, I wish you all the best!

**Comment by kylebjordahl** [comment]
Thanks!
