### ISSUE TITLE
Local intra-project dependencies not registered

### ISSUE THREAD

**Issue by kylebjordahl** [lucasvieirasilva/nx-plugins#193]
### Current Behavior

Dependencies between local projects do not appear in the Nx graph.

### Expected Behavior

Dependencies between projects (when added with `nx run myapp:add --name=mylib --local`) should result in dependencies in the output of the Nx graph.

### Steps to Reproduce

1. Scaffold two projects, `myapp` and `mylib`
2. `add` one project to the other: `nx run myapp:add --name=mylib --local`
3. run `nx graph --file=output.json && cat output.json` and inspect the `graph.dependencies` section
4. No dependencies listed for `myapp`

### Nx Report

```shell
Node   : 20.11.1
OS     : linux-arm64
npm    : 10.2.4

nx                 : 18.0.7
@nx/js             : 18.0.7
@nx/jest           : 18.0.7
@nx/linter         : 18.0.7
@nx/eslint         : 18.0.7
@nx/workspace      : 18.0.7
@nx/cypress        : 18.0.7
@nx/devkit         : 18.0.7
@nx/eslint-plugin  : 18.0.7
@nx/plugin         : 18.0.7
@nx/react          : 18.0.7
@nx/remix          : 18.0.7
@nx/storybook      : 18.0.7
@nrwl/tao          : 18.0.7
@nx/vite           : 18.0.7
@nx/web            : 18.0.7
typescript         : 5.3.3
---------------------------------------
Community plugins:
@nxlv/python : 18.0.0
```

### Additional Information

Its possible that something broke as part of the change to Project Crystal in Nx@18. I'll see if I can get anything working on a fork for now.

**Comment by lucasvieirasilva** [comment]
@kylebjordahl did you add "@nxlv/python" to the `nx.json` > `plugins` array?

```json
{
  "$schema": "./node_modules/nx/schemas/nx-schema.json",
  ...
  "plugins": [
    "@nxlv/python",
    ...
    }
  ]
}
```

![image](https://github.com/lucasvieirasilva/nx-plugins/assets/12723594/4d63793a-5e02-441d-b3cd-d41aa948c3b0)

**Comment by kylebjordahl** [comment]
GAH. That was it. I thought `nx add` would also add to the plugin.
