### ISSUE TITLE
Paid Support?

### ISSUE THREAD

**Issue by shannonlal** [lucasvieirasilva/nx-plugins#196]
Does anyone offer any paid support?  I am looking to integrate this into our current monorepo but we have been having some issues with our CI (Github Actions) and could use a bit help

- [ ] I'd be willing to implement this feature

I am currently working to get NXPython integrated into an existing monorepo that has some frontend react and typescript projects.  We are pretty close to getting it working but could use a bit of help to get it working.  I just wanted to see if anyone does any consulting on this

## Motivation

Trying to get this integrated into our production environment and could use some help

**Comment by lucasvieirasilva** [comment]
@shannonlal can we talk here? https://discord.gg/pvNFA45JXf

**Comment by shannonlal** [comment]
@lucasvieirasilva I just joined the discord channel
