### ISSUE TITLE
Failed to set app as affected by package dependency changes

### ISSUE THREAD

**Issue by yaringalmor** [lucasvieirasilva/nx-plugins#250]
### Current Behavior

Changes made to a dependency package (declared by pyproject.toml file) is not affecting consuming app.

### Expected Behavior

Set the consuming app as affected per any changes made within the package.

### Steps to Reproduce

I was following this [article](https://betterprogramming.pub/poetry-python-nx-monorepo-5750d8627024)

1. Create project using the following command - 
```
npx nx generate @nxlv/python:poetry-project proj1 \
--projectType application \
--description='My Project 1' \
--packageName=pymonorepo-proj1 \
--moduleName=pymonorepo_proj1
--directory packages/proj1
```

2. Create package using the following command - 
```
npx nx generate @nxlv/python:poetry-project lib1 \
--projectType library \
--description='My Library 1' \
--packageName=pymonorepo-lib1 \
--moduleName=pymonorepo_lib1
```

3. Set the package as a dependency of the project - 
```
npx nx run proj1:add --name lib1 --local
``` 

4. Checking affected graph
```
npx nx graph --affected
```

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 22.9.0
OS     : darwin-arm64
pnpm   : 9.6.0

nx (global)  : 19.2.0
nx           : 19.2.0
@nx/js       : 19.2.0
@nx/eslint   : 19.2.0
@nx/plugin   : 19.2.0
typescript   : 5.4.5
---------------------------------------
Community plugins:
@nxlv/python : 18.1.0
```

**Comment by lucasvieirasilva** [comment]
@yaringalmor I've noticed you are using the `@nxlv/python` version `18.1.0`, could you try it with the [19.1.3](https://www.npmjs.com/package/@nxlv/python/v/19.1.3) version?

I couldn't reproduce with the [19.1.3](https://www.npmjs.com/package/@nxlv/python/v/19.1.3) version.

![image](https://github.com/user-attachments/assets/da4c5491-070c-4902-b5d6-898346274197)
![image](https://github.com/user-attachments/assets/5a271739-9204-4de8-a0e7-b3ba48abb008)

Have you added the following to your `nx.json`?

```json
{
  ...
  "plugins": [
    "@nxlv/python"
  ]
}
``` 

My nx report

```
 NX   Report complete - copy this into the issue template

Node   : 20.17.0
OS     : darwin-x64
npm    : 10.8.2

nx             : 19.2.0
@nx/js         : 19.2.0
@nx/workspace  : 19.2.0
@nx/devkit     : 19.2.0
@nrwl/tao      : 19.2.0
typescript     : 5.6.2
---------------------------------------
Registered Plugins:
@nxlv/python
---------------------------------------
Community plugins:
@nxlv/python : 19.1.3
```
