### ISSUE TITLE
Nx 20 support

### ISSUE THREAD

**Issue by hschmidtchen** [lucasvieirasilva/nx-plugins#253]
## Description

Update the @nxlv/python plugin to support Nx 20.

## Motivation

Nx 20 includes important bugfixes for Nx which are not available in Nx v19 and the @nxlv/python package is currently causing conflicts due to its dependency on @nrwl/devkit at version 19.

## Suggested Implementation

Update the @nxlv/python plugin to use @nx/devkit v20 (note that [@nrwl/devkit](https://www.npmjs.com/package/@nrwl/devkit) was deprecated and is now continued as [@nx/devkit](https://www.npmjs.com/package/@nx/devkit))

@lucasvieirasilva can you share if you are planning to upgrade any time soon?

**Comment by lucasvieirasilva** [comment]
Hi @hschmidtchen, thanks for raising this issue, I'll try to release a 20.x release until the end of this week

**Comment by hschmidtchen** [comment]
Thanks a lot for the fast release @lucasvieirasilva!

I can confirm that the dependency conflict is resolved with the update.
