### ISSUE TITLE
No license on the @nxlv/python plugin.

### ISSUE THREAD

**Issue by niall-mediasuite** [lucasvieirasilva/nx-plugins#4]
I have noticed there is an MIT license on the top level but this is not present in the individual package and therefore doesn't show up on NPM. I would appreciate if you could clarify the licensing on the @nxlv/python package.

**Comment by lucasvieirasilva** [comment]
@niall-mediasuite nice catch, I've added the `license` property to the `@nxlv/python` package, see:

<img width="457" alt="image" src="https://user-images.githubusercontent.com/12723594/211664732-96405c72-0574-4c60-8494-ab8c49da6a9f.png">
