### ISSUE TITLE
Support Django

### ISSUE THREAD

**Issue by WCN-llc** [lucasvieirasilva/nx-plugins#96]
Hello!
Nice plugin!
Does this plugin have the ability to add Django?

**Comment by WCN-llc** [comment]
Star! :-)

**Comment by lucasvieirasilva** [comment]
Hey @WCN-llc, thanks.

Yes, it does, you can add any Python library you want by using the Nx executors (e.g. `npx nx run <myproject>:add --name numpy`.

You can also use `npx nx build <myproject>` to generate the .whl artifact file with all external + local dependencies and use it in a Docker container, serverless functions, etc.

I wrote this article about it: https://medium.com/better-programming/poetry-python-nx-monorepo-5750d8627024

**Comment by WCN-llc** [comment]
> Hey @WCN-llc, thanks.
> 
> Yes, it does, you can add any Python library you want by using the Nx executors (e.g. `npx nx run <myproject>:add --name numpy`.
> 
> You can also use `npx nx build <myproject>` to generate the .whl artifact file with all external + local dependencies and use it in a Docker container, serverless functions, etc.
> 
> I wrote this article about it: https://medium.com/better-programming/poetry-python-nx-monorepo-5750d8627024

@lucasvieirasilva 

Thank you so much, friend! :-)
